# The URL the site will be built for
base_url = "https://almostearthling.github.io"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "linkita"

author = "almostearthling"
title = "Personal GitHub Site"
description = "GitHub Pages Site of Francesco Garosi (AlmostEarthling)"


[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

[extra.profiles.almostearthling]
name = "Francesco Garosi"
avatar_url = "/icons/almostearthling.jpg"
avatar_alt = "AlmostEarthling"
social = [
    { name = "github", url = "https://github.com/almostearthling" },
    { name = "codeberg", url = "https://codeberg.org/almostearthling" },
]
